### ISSUE TITLE
New release 0.4.4

### ISSUE THREAD

**Issue by headlessme** [unrelentingtech/SwiftCBOR#64]
Any plans to tag a 0.4.4 release with the changes merged in October?

**Comment by MaxDesiatov** [comment]
+1 here, a new release would be great

**Comment by hamchapman** [comment]
0.4.4 has been tagged and pushed to CocoaPods. 

Let me know if there are any issues. It's the first release in a while and a decent amount has changed both inside the library and externally in terms of Xcode, CocoaPods, etc etc
