### ISSUE TITLE
Breaking Changes in 0.4.5

### ISSUE THREAD

**Issue by chickdan** [unrelentingtech/SwiftCBOR#81]
It looks like there were many changes implemented in 0.4.5, some of which were breaking changes preventing other dependencies from compiling because they no longer conform to `CBOREncodable`, for example. Can you please revert the release and re-release using a major version bump so that package managers don't accidentally pull in breaking changes? Thank you.

**Comment by hamchapman** [comment]
As the library is pre-1.0.0 the typical semantic versioning rules don't apply, but I do appreciate that this may have been frustrating and disruptive for you and so sorry for that. 

At this point though I think it could end up being more disruptive for users if 0.4.5 (and 0.4.4 would also need to go, IIRC) were to be removed.

**Comment by eddieSullivan** [comment]
I agree that removing the releases once they're out would cause more problems than it would solve.

I also see your point about the library being pre-1.0.0. While technically that should mean clients should expect any change to be breaking, in practice these days many many libraries never get to that 1.0.0 version, and so we have come to rely on the ability to bring in patch versions without breaking. Just something to keep in mind for the future.
